sets={1,23,7}
print(type(sets))
#conversion
# print(type(sets))
# print(type(my_list))
print(sets)
sets.add(4)
sets.add(5)
print(sets)
sets.remove(23)
print(sets)
sets.pop()
print(sets)
sets.update("578")
print(sets)